FROM alpine:3.1

# Update
RUN apk add --update nodejs

# Install app dependencies
COPY package.json /node-todo/package.json
RUN npm install

# Bundle app source
#COPY . /src

EXPOSE  8080
CMD ["node", "server.js"]